---
# This role installs dovecot-libsodium-plugin for better password hashing.

- name: install dovecot-dev
  package: name=dovecot-dev state=latest

- name: install libsodium-dev
  package: name=libsodium-dev state=latest

- name: clone libsodium-dovecot-plugin over public internet
  shell: |
    git -C /usr/src clone https://github.com/LuckyFellow/dovecot-libsodium-plugin.git
  args:
    creates: /usr/src/dovecot-libsodium-plugin
  when: use_tor != 'true'

- name: clone libsodium-dovecot-plugin through tor
  shell: |
    git -C /usr/src clone https://github.com/LuckyFellow/dovecot-libsodium-plugin.git
  args:
    creates: /usr/src/dovecot-libsodium-plugin
  when: use_tor == 'true'
  environment:
    ALL_PROXY: '{{ tor_proxy_url | quote }}'

- name: build and install dovecot-libsodium-plugin
  shell: |
    ./autogen.sh
    ./configure --prefix=/usr --with-moduledir=/usr/lib/dovecot/modules
    make
    make install
  args:
    chdir: /usr/src/dovecot-libsodium-plugin
    creates: /usr/lib/dovecot/modules/auth/libsodium_plugin.so
  notify:
    - restart dovecot
