---
# This role installs fail2ban with all defaults

- name: Install fail2ban
  package: name=fail2ban state=latest
- name: Touch some files fail2ban expects
  file:
    name: /var/log/mail.warn
    state: touch
- name: Enable and start fail2ban
  service: name=fail2ban state=started enabled=yes

# In the future, this task may be replaced with a
# sensible "blockinfile" task to just define defaults 
# for all servers. This will allow us to idempotently
# use "blockinfile" elsewhere for the likes of postfix
# or dovecot jails without triggering a restart of
# the service here. This will do for now though.
- name: template /etc/fail2ban/jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 644
    backup: yes
  notify:
    - restart fail2ban
